version: "3"
services:
  visualizer:
    image: manomarks/visualizer:latest
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=swarm.p.cns.me
        - com.df.servicePath=/
        - com.df.port=8080
        - com.df.redirectWhenHttpProto=true
        - com.df.xForwardedProto=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  proxy:
    external: true

