version: "3"
services:
  visualizer:
    image: dockersamples/visualizer:latest
    healthcheck:
      test: "wget -q -O > /dev/null localhost:8080 || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - proxy
    read_only: true
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 16M
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=swarm.p.cns.me
        - com.df.servicePath=/
        - com.df.port=8080
        - com.df.httpsOnly=true
        - com.df.redirectWhenHttpProto=true
        - com.df.xForwardedProto=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  proxy:
    external: true

