version: "3"
services:
  visualizer:
    image: dockersamples/visualizer:latest
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 16M
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=swarm.p.cns.me
        - com.df.servicePath=/
        - com.df.port=8080
        - com.df.httpsOnly=true
        - com.df.xForwardedProto=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  proxy:
    external: true

